from turtle import *

#we want to paint a hosue

#step 1:  draw a square
speed(70)
width(7)
color("black")
forward(200)
left(90)

forward(200)
left(90)

forward(200)
left(90)

forward(200)
left(90)

#end of square

#drawing a door

forward(70)
color("black")
begin_fill()
left(90)
forward(120)
right(90)
forward(60)
right(90)
forward(120)
end_fill()
penup()
goto(200, 200)
pendown()

color("black")
begin_fill()
right(150)
forward(200)
left(120)
forward(200)
end_fill()

color("green")
penup()
goto(0, 160)
left(120)
forward(15)
left(90)
forward(25)
right(90)
pendown()
begin_fill()
forward(45)
right(90)
forward(45)
right(90)
forward(45)
right(90)
forward(45)
penup()
right(90)
forward(120)
pendown()
forward(45)
right(90)
forward(45)
right(90)
forward(45)
right(90)
forward(45)
end_fill()


left(90)
penup()
forward(470)
left(90)
forward(80)
pendown()
circle(120)
color("black")
begin_fill()
circle(120)
end_fill()
color("white")
penup()
right(270)
forward(120)
pendown()
left(180)
penup()
forward(72.5)
left(90)
forward(35)

write("G   A", font=("Arial", 50, "bold italic"))
color("green")
write("   O", font=("Arial", 50, "bold italic"))


goto(0,0)
left(180)
forward(210)
right(90)
forward(10)
color("white")
write(" A", font=("Arial", 22, "bold italic"))
color("green")
write("    C", font=("Arial", 22, "bold italic"))
color("white")
write("       A", font=("Arial", 22, "bold italic"))
color("green")
write("          D", font=("Arial", 22, "bold italic"))
color("white")
write("             E", font=("Arial", 22, "bold italic"))
color("green")
write("                M", font=("Arial", 22, "bold italic"))
color("white")
write("                   Y", font=("Arial", 22, "bold italic"))
penup()
left(90)
color("green")
forward(40)
right(90)
forward(36)
write("GOA", font=("Arial", 35, "bold italic"))
color("black")
penup()
right(90)
forward(400)
right(90)
forward(170)
write("ANDRO", font=("Arial", 70, "bold italic"))
left(90)
forward(85)
right(90)
forward(150)
write("ZAZUNISHVILI", font=("Arial", 70, "bold italic"))
forward(210)
left(90)
forward(160)
color("gray")
write("👩‍💻", font=("Arial", 50, "bold italic"))
color("green")
write("​     Sally-ს რაზმი", font=("Arial", 50, "bold italic"))







exitonclick()